language: ruby
rvm:
  - "2.1.1"
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database autastic_test;' -U postgres

script: 'bundle exec rake'
